# Debian dkms packages that need binary packages.
# Unfortunately not all names are standard and therefore we need todo the package generation our self.
# 
# ${SOMETHING} will be substituted
kernel:
  kbuild-version: "6.1" # Unfortunately the kbuild packages have a different name
  version: "6.1.0-0.deb11.7" # Version in the package name
  package-version: "6.1.20-2~bpo11+lernstick.1" # Specify specific version of the package
  arch: amd64
  arch-cpu: "x86_64"

# Set to path to enable local package repository
local-repo: false


# Set distribution for created Debian packages
distribution: "lernstick-11"


# Output dir
output-dir: "/packages"

packages:
  broadcom-sta-dkms:
    dkms: broadcom-sta
    result: broadcom-sta-modules
    template-dir: /broadcom-sta-template
  v4l2loopback-dkms:
    dkms: v4l2loopback
    result: v4l2loopback-modules
    template-dir: /debian-template
  rtl88x2bu-dkms:
    dkms: rtl88x2bu
    result: rtl88x2bu-modules
    template-dir: /debian-template
  nvidia-kernel-dkms:
    dkms: nvidia-current
    result: nvidia-kernel-${MODULE_VERSION}
    template-dir: /nvidia-template
  nvidia-legacy-390xx-kernel-dkms:
    dkms: nvidia-legacy-390xx
    result: nvidia-legacy-390xx-kernel-${MODULE_VERSION}
    template-dir: /nvidia-template
  virtualbox-dkms:
    dkms: virtualbox
    result: virtualbox-modules
    template-dir: /debian-template
